[package]
name = "ds_proxy"
version = "0.1.0"
authors = ["simon lehericey <mail@simon.lehericey.net>"]
edition = "2018"
build = "build.rs" # Cargo only supports one build script per project at the moment

[dependencies]
sodiumoxide = "0"
futures = "0"
futures-core = "0"
actix-web = { version="3", features = ["openssl"] }
actix-rt = "1"
actix-http = "*"
actix-files = "*"
bytes = "0"
docopt = "1"
serde = { version = "1", features = ["derive"] }
log = "0"
env_logger = "0"
sentry = "0"
sentry-actix = "0"

[dev-dependencies]
assert_cmd = "1"
assert_fs = "1"
proptest = "0"
rand = "0"
serial_test = "0"
serde_json = "*"
uuid = { version = "0", features = ["v4"] }
