[package]
name = "encrypt"
version = "0.1.0"
authors = ["simon lehericey <mail@simon.lehericey.net>"]
edition = "2018"
build = "build.rs" # Cargo only supports one build script per project at the moment

[dependencies]
sodiumoxide = "0.2.2"
futures = "0.3.5"
futures-core = "0.3.5"
actix-web = { version="3.0.0-alpha.3", features = ["openssl"] }
actix-rt = "1.0"
bytes = "0.5.3"
docopt = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.6"
sentry = "0.12.0"

[dev-dependencies]
assert_cmd = "0.11"
assert_fs = "0.11"
proptest = "0.9.4"
rand = "0.6.5"
serial_test = "0.4.0"
uuid = { version = "0.8", features = ["v4"] }
