[package]
name = "encrypt"
version = "0.1.0"
authors = ["simon lehericey <mail@simon.lehericey.net>"]
edition = "2018"
build = "build.rs" # Cargo only supports one build script per project at the moment

[dependencies]
sodiumoxide = "0.2.6"
futures = "0.3.5"
futures-core = "0.3.5"
actix-web = { version="3.0.0-beta.3", features = ["openssl"] }
actix-rt = "1.1.1"
bytes = "0.5.6"
docopt = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.7"
sentry = "0.19"
sentry-actix = "0.19"

[dev-dependencies]
assert_cmd = "1"
assert_fs = "1"
proptest = "0.10"
rand = "0.7"
serial_test = "0.5"
uuid = { version = "0.8", features = ["v4"] }
