[package]
name = "encrypt"
version = "0.1.0"
authors = ["simon lehericey <mail@simon.lehericey.net>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.2"
futures = "0.1.27"
actix-web = { version="1.0.2", features=["ssl"] }
bytes = "0.4.12"
futures-fs = "0.0.5"
docopt = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.6"

[dev-dependencies]
rand = "0.6.5"
assert_cmd = "0.11"
assert_fs = "0.11"
proptest = "0.9.4"