[package]
name = "encrypt"
version = "0.1.0"
authors = ["simon lehericey <mail@simon.lehericey.net>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.1"
futures = "0.1.25"
actix-web = { version="1.0.0-beta.1", features=["ssl"] }
bytes = "0.4.12"
futures-fs = "0.0.5"
docopt = "1"
serde = { version = "1", features = ["derive"] }
lazy_static = "1.3.0"